GET http://localhost:5162/games

###
GET http://localhost:5162/games/1

###
POST http://localhost:5162/games
Content-Type: application/json

{
    "name": "CS:GO",
    "genreId": 1,
    "price": 50.2,
    "releaseDate": "1990-03-10"
}

###
PUT http://localhost:5162/games/2
Content-Type: application/json

{
    "name": "Call Of Duty",
    "genre": "Action",
    "price": 19.2,
    "releaseDate": "2020-02-02"
}

###
DELETE  http://localhost:5162/games/1